### ISSUE TITLE
Cannot access Modelica Map file---- .esim folder no section: 'esim'

### ISSUE THREAD

**Issue by lrchaudhari** [FOSSEE/eSim#154]
When try to run esim.exe application file after installation I received above error and command window close with no output. 
Windows 10 pro 64 bit 

![esim error ](https://user-images.githubusercontent.com/66740990/84289588-4caf7a00-ab60-11ea-9a41-90a91492977f.png)

**Comment by rahulp13** [comment]
Check if .eSim folder is present in the Profile/Home path i.e. C:/Users/<username>/

**Comment by lrchaudhari** [comment]
Dear Rahul
Thanks for replay
.esim folder is is present in c:\uses\user folder is it required to copy in
each user account folder?
 problem arises when I try to open eSIm form user account instead of admin
account
Thanks
Lalit Chaudhari

**Comment by rahulp13** [comment]
Certain eSim dependencies are configured based on the user account through which it was installed. So you need to use that user account for its proper functioning. However, you can try replicating them and let me know if it works.

**Comment by lrchaudhari** [comment]
Thanks for help I will check and let you know
Lalit Chaudhari
