### ISSUE TITLE
Missing LLVM-8 during installation script

### ISSUE THREAD

**Issue by geraldsweers** [FOSSEE/eSim#163]
Missing LLVM-8 during installation script

Looks i have installed LLVM12.0-52

Cant find it the config file (im still a newbe)

**Comment by Eyantra698Sumanto** [comment]
The whole system of eSim is designed to work using kicad-4.0.7. Newer versions of kicad not supported. Use the kicad supported by eSim.

**Comment by Eyantra698Sumanto** [comment]
We would include KiCAD 5.1 in newer release of eSim. Please let us know if you would like to contribute
