### ISSUE TITLE
eSim splash screen hides the workspace dialoge box on launch

### ISSUE THREAD

**Issue by kavyamanohar** [FOSSEE/eSim#45]
On Ubuntu 15.04 operating system upon launching eSim, the splash screen hides the dialogue box which prompts the user to choose the workspace location. Unless the workspace location is not chosen eSim wont be launched. User unaware of the dialogue box in the background might have to wait endlessly for eSim to launch. However upon a mouse click the splash screen  quits itself and  the workspace dialogue box becomes visible . 

The splash screen should either disappear after a time out period or the the workspace dialogue box should be above the splash screen.

**Comment by fahim-oscad** [comment]
Thanks for reporting issue and giving suggestion. I have tested it on Ubuntu 12.04,14.04 and Windows 7. And in my machine the workspace window is coming on the top of splash screen. 

Let me check if the issue is only with 15.04.

**Comment by fahim-oscad** [comment]
I check it on Ubuntu 15.04 and its working perfectly. Looks like its machine specific.

**Comment by kavyamanohar** [comment]
Sorry, I missed to mention that the above issue was while launching eSim with KDE on Ubuntu 15.04.
It works well with Unity.

**Comment by fahim-oscad** [comment]
Thank you for your valuable inputs. We will definitely change it in next version.
