### ISSUE TITLE
Add feature to rename projects

### ISSUE THREAD

**Issue by nilshah98** [FOSSEE/eSim#82]
Add feature to rename projects, and also their respective files, in the selected folder.

May port code from 2018 interns work, refer - 5e58022d8413f3ac6608cfac06ba91f3ee1a3840

**Comment by sunilshetye** [comment]
Create three projects named **a**, **ab**, and **b**. Test cases for this issue:

1. Rename **a** to _blank_: Should fail saying cannot give empty project name.
2. Rename **a** to **a**: Should fail saying that project name has to be different.
3. Rename **a** to **b**: Should fail saying that **b** is an existing project.
4. Rename **a** to **c**: Only project **a** should be renamed to **c**. **ab** should not be renamed.

**Comment by anjalijaiswal08** [comment]
Okay, will look into it. Thank you.

**Comment by saurabhb17** [comment]
has this been resolved?

**Comment by anjalijaiswal08** [comment]
> has this been resolved?

Yes, it has been solved, will push it today only. Thank you.

**Comment by sunilshetye** [comment]
merged into fellowship2019-python3 branch
