### ISSUE TITLE
Change format of .lib files from multiple lines to single lines

### ISSUE THREAD

**Issue by nilshah98** [FOSSEE/eSim#91]
**Issue details-**
- Currently the generated `.lib` files follow the multi line format, change it to single line format for easier use
- Device models to be generated according to the Spice's convention. Example -
- Multi Line format -
```
.MODEL PowerDiode D(
+ Vj=.75
+ Nbvl=14.976
+ Cjo=175p
+ Rs=.25
+ Isr=1.859n
+ Eg=1.11
)
```
- Single Line format -
```
.MODEL PowerDiode D( Vj=.75 Nbvl=14.976 Cjo=175p Rs=.25 Isr=1.859n Eg=1.11 )
```
Edit: Add relevant tags such as `feature` or `enhancement`
Edit: Added spice format for reference

**Comment by saurabhb17** [comment]
please rephrase it as " device models to be generated according to Spice's convention"

**Comment by sunilshetye** [comment]
merged into fellowship2019-python3 branch
